### PR TITLE
replace non-ascii by space

### PR DESCRIPTION
**Pull request by alaindargelas**

### CODE REVIEW

**Comment by Thomasb81** [comment]
Does that mean that source code can contain non ascii character ?
According to annex A.9.2, even comments should restrict to ascii symbol...

**Comment by alaindargelas** [comment]
There is the standard, and what the commercial tools do support, some files contain non ascii character in comments and are widely accepted.
Surelog was too restrictive.

**Comment by Thomasb81** [comment]
I observe and understand that.

From my point of view :
It has value to be able to track/log such discrepancy with the standard  : It remains work : implement standard, analyze issues, find work-around.
Such a list can by itself serve as promotional material as could be api documentation, command line help for the tool...

**Comment by alaindargelas** [comment]
#2243 adds a Note when non-ascii character is found.

**Pull request merged**
