### PR TITLE
Fix TypedefRange test

### PR DESCRIPTION
**Pull request by RRozak**
In TypedefRange test there were range nodes duplicated.

### CODE REVIEW

**Comment by RRozak** [comment]
@alaindargelas, could you provide an instruction how to automatically update the log files in tests?

**Comment by alaindargelas** [comment]
https://github.com/chipsalliance/Surelog/blob/master/src/README.md

cd build
../tests/regression.tcl update

**Comment by RRozak** [comment]
I tried it and all logs became empty. 
Maybe there is a problem with paths. I will check.

**Comment by RRozak** [comment]
The problem was I didn't have `time` tool installed. Now it works.

**Comment by alaindargelas** [comment]
Please push the new log files

**Comment by RRozak** [comment]
Ok. I see that I broke the ArianeElab test.

**Comment by RRozak** [comment]
I think that the problem is more general. Packed arrays of enums are not parsed properly also when they are the members of structs. I created the issue: https://github.com/chipsalliance/Surelog/issues/1487

**Comment by alaindargelas** [comment]
I'm dismissing this pull request. It was an incorrect fix. #1490 fixes this particular issue.
Please create an issue before creating a pull request next time, it'll be easier to discuss.

**Pull request closed without merging**
