### PR TITLE
Start adding a usage message to roundtrip if invoked w/o parameter.

### PR DESCRIPTION
**Pull request by hzeller**
The details need to still be filled in, 'base-dir' and 'log-dir'
are not quite clear what they are.

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
I wanted to play with the roundrip tool, but it is not quite clear to me yet how to use it. So I started a usage message that we can update to be more detailed later.

**Review by hs-apotell — APPROVED** [review]
LGTM

**Comment by alaindargelas** [comment]
@hs-apotell how do we update the logs files with the roundtrip section?

**Comment by hs-apotell** [comment]
roundtrip is part of default regression run and updates the log files. To update the logs using regression script 
```
python3 regression.py update
```

**Pull request merged**
