### PR TITLE
Make uhdm includes qualified within uhdm-directory.

### PR DESCRIPTION
**Pull request by hzeller**
As preparation to switch to latest UHDM head.

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
After this, and this UHDM PR https://github.com/chipsalliance/UHDM/pull/494 is merged, it should be safe to update Surelog to head of UHDM.

**Comment by alaindargelas** [comment]
Oh, I see, I can merge now?

**Comment by hzeller** [comment]
Yes, after this is merged, UHDM head should also work.
So you can merge this first (should work)
and then update the UHDM submodule to take it from head (and that should also work)

**Comment by hzeller** [comment]
(or should I merge small changes that don't destroy things like this myself ?)

**Pull request merged**
