### PR TITLE
[RFC] init nix-shell development environment

### PR DESCRIPTION
**Pull request by sjkelly**
This is a nix-shell environment for building Surelog. Nix shells can be helpful for ensuring local development and CI environments match, among other benefits. 

With a nix install you can simply do:
```
nix-shell
make 
make install
```

There are some tweaks that are required for fully hermetic and reproducible builds (ANTLR4 is the main suspect). I am working on those fixes [here](https://github.com/RAPcores/rapcores/blob/sjk/sv-ng1/nix/surelog.nix), with the objective of eventual upstreaming in nixpkgs.

I'm labeling this RFC since Nix is somewhat niche, and totally get not wanting some weird package manager you don't use polluting the repo :).

### CODE REVIEW

**Comment by hzeller** [comment]
Very nice!

Nix is a good way to implement dependency management and repeatable builds and I wish more people would use it, so this is a welcome addition.

In this pull request, can you add a line in [INSTALL.md](https://github.com/chipsalliance/Surelog/blob/master/INSTALL.md) ? Maybe after the install line for debian-based systems, something along the lines of

  *  In a [nix environment](https://nixos.org/) simply type `nix-shell` to set up the dependencies.

**Comment by alaindargelas** [comment]
@sjkelly, please add the comment above and we are good to merge.

**Comment by sjkelly** [comment]
I took the liberty of structuring the Install guide while I was there. Please be sure to review.

**Comment by hzeller** [comment]
@sjkelly what is the state of your nixpkgs upstream effort ? Would be great to have it available there.

**Comment by sjkelly** [comment]
It got stalled out due to a job change. Some useful derivations are in here
for reference: https://github.com/RAPcores/rapcores/tree/main/nix

For what it's worth I will likely end up packaging Surelog for Julia in the
near future though.

**Pull request merged**
