### PR TITLE
Fix parameters with correct type to compileTypespec.

### PR DESCRIPTION
**Pull request by hzeller**
Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Calls to the [`compileTypespec()`](https://github.com/chipsalliance/Surelog/blob/master/src/DesignCompile/CompileHelper.h#L211-L216) method seem to be off - an empty string at the end was interpreted as boolean `true` by accident, so this first version of this pull request just replaces that with what the compiler sees, however, this is certainly due to some shift in added parameters at some point.

The default value of that parameter `isVariable` would be false. Is that the intended value ? If so, then I can just remove the `true` at the end.

**Comment by hzeller** [comment]
(marked as draft, as it is not meant to be submitted until the intended value has been determined)

**Review by alaindargelas — COMMENTED** [review]
It should be false instead of true

**Comment by hzeller** [comment]
Alright, removed the parameter entirely, so that the default value for that parameter (`false`) is used.

**Pull request merged**
