### PR TITLE
Update antlr submodule.

### LINKED ISSUE #3081: Latest Antlr broken on Clang
https://github.com/chipsalliance/Surelog/runs/7143585776?check_suite_focus=true

@hzeller, @mithro, you might want to direct to the proper channels.

### PR DESCRIPTION
**Pull request by hzeller**
Fixes #3081

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by alaindargelas** [comment]
More Windows breakage in Antlr:
FAILED: third_party/antlr4/runtime/Cpp/runtime/CMakeFiles/antlr4_static.dir/src/CharStream.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x64\cl.exe  /nologo /TP -DANTLR4CPP_STATIC -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\atn -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\dfa -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\internal -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\misc -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\support -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\tree -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\tree\pattern -ID:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\tree\xpath /DWIN32 /D_WINDOWS /GR /EHsc   -Wall -pedantic -W /O2 /Ob2 /DNDEBUG -O3 -DNDEBUG  -MT /wd4251  -std:c++17 /showIncludes /Fothird_party\antlr4\runtime\Cpp\runtime\CMakeFiles\antlr4_static.dir\src\CharStream.cpp.obj /Fdthird_party\antlr4\runtime\Cpp\runtime\antlr4-runtime-static.pdb /FS -c D:\a\Surelog\Surelog\third_party\antlr4\runtime\Cpp\runtime\src\CharStream.cpp
cl : Command line error D8004 : '/W' requires an argument
ninja: build stopped: subcommand failed.
make: *** [Makefile:22: release] Error 1
Error: Process completed with exit code 2.

**Comment by hs-apotell** [comment]
Changes were introduced between the time I created the PR and the same got accepted and merged. Incidentally, there is no CI verification build for Windows + MSVC for antlr and so none of these issues get caught when they should be. There were number of issues in the Cpp runtime's CMakeFile.txt. Here's the PR to fix these issues - https://github.com/antlr/antlr4/pull/3777

**Comment by hzeller** [comment]
@hs-apotell 's PR has been accepted, I've now updated the submodule again, let's see what happens.

**Comment by hzeller** [comment]
The remaining issue in the CI has something to do with CoresSweRVMP.log which was broken before.

**Pull request merged**
