### PR TITLE
Allow for non-vendored Antlr, UHDM, Googletest, etc

### PR DESCRIPTION
**Pull request by timkpaine**
Followup to https://github.com/chipsalliance/Surelog/pull/3182

Work in progress, opened this draft PR for tracking (apologies for noise)

### CODE REVIEW

**Comment by alaindargelas** [comment]
@timkpaine, now that https://github.com/chipsalliance/UHDM/pull/874 is merged, please amend this PR with it.
Also, since cmake needs to be upgraded to 3.20 at minimum, please update the requirements in the .md file(s).

**Comment by timkpaine** [comment]
Absolutely, been working on it. Would you mind cutting a 1.46 release of UHDM, those changes were necessary to facilitate a few publication mechanisms (homebrew and conda forge)

**Comment by alaindargelas** [comment]
@hzeller can you help here? Do we have an actual UHDM release number?

**Comment by hzeller** [comment]
ah, nice, thanks for this work.

UHDM release numbers are still somewhat manual, but process is described in #3160 - I have to get back to that issue to complete. I'll see that I can add a fresh tag in UHDM tomorrow.

**Comment by timkpaine** [comment]
im going to start making the modifications to GitHub actions as with UHDM to test the vendoring, please don’t allow workflows on this PR or you’ll get spammed a lot (I’m running the actions on my fork instead)

**Comment by timkpaine** [comment]
have to fix some paths to grab the correct headers, need to sleep now but will do tomorrow

**Comment by hzeller** [comment]
FYI, both Surelog and UHDM are now tagged with the latest version v1.48, based on when the last version was bumped in Surelog ( https://github.com/chipsalliance/Surelog/commit/71eb4028f18d6b12833578fbcfa4db7b06869f78 ) then tagging that hash as well as the hash that was active as submodule in Surelog at the time.

  * https://github.com/chipsalliance/Surelog/releases/tag/v1.48
  * https://github.com/chipsalliance/UHDM/releases/tag/v1.48

**Comment by timkpaine** [comment]
I'm still finishing 1 build issue where the install include path is being set to `/` instead of e.g. `/usr/include`. It only seems to be affecting the include dir, and only on the non-vendored code path, so im hoping its a simple fix. I will temporarily close this PR if i cant repro on my ubuntu machine exactly whats going on in CI so i don't make a bunch of email noise for everyone with a lot of experimental pushes.

**Comment by timkpaine** [comment]
missing `include(GNUInstallDirs)` silently leaves all install variables unset, which means `${CMAKE_INSTALL_LIBDIR}/surelog` turns into `/surelog`. We would've never noticed because it was included by third party's CMakeLists, which hoists it into all cmake files' scope....... 😡cmake....

**Comment by timkpaine** [comment]
build / build-tests all working now, just looking at some regression test failures

**Comment by hzeller** [comment]
Let me know when you're ready to have the Surelog CI approved to run.

**Comment by timkpaine** [comment]
just waiting for the latest build to go all green: https://github.com/timkpaine/Surelog/actions/runs/4378815502

**Comment by timkpaine** [comment]
Looks all good on my end

Screenshot 2023-03-09 at 17 12 19

**Comment by hzeller** [comment]
Alright, this looks very good. 
@alaindargelas @hs-apotell any last review comments before merge ?
I guess the main concern of @hs-apotell would be if the submodule thing would still work as it is not easy to get pre-packaged stuff on Windows, and the answer is yes, submodules would keep working.

**Comment by alaindargelas** [comment]
All good on my end, let's give @hs-apotell a chance for review.

**Review by alaindargelas — DISMISSED** [review]

**Comment by timkpaine** [comment]
Note that FindIHDM can be removed once https://github.com/chipsalliance/UHDM/pull/875/commits/5b3469dc486684c0ecdff2e5affc58a107c8d163 gets merged

**Comment by timkpaine** [comment]
ive swapped these back, was just a convenience since the `surelog` target wouldn't have been defined at that point

**Comment by Thomasb81** [comment]
Is this PR related to https://github.com/chipsalliance/Surelog/issues/2353 ?
If yes could we close the related issue ?

**Comment by hzeller** [comment]
Yes, this addresses exactly what #2353 raised, and so with @timkpaine 's work, this is finally finished. I closed the other issue.

**Pull request merged**
