### PR TITLE
Make sure variable that is used as input parameter is initialized.

### PR DESCRIPTION
**Pull request by hzeller**
Found with `msan`.

### CODE REVIEW

**Comment by hzeller** [comment]
This will change the logfiles for `ArianeElab`, `ArianeElab2`, and `BlackParrotMuteErrors`.

What is the recommended standard way these days to update the logfiles in git from the regression run ?

**Comment by hzeller** [comment]
Note, this still needs the logfile update (but I didn't know how to create that with the current script). Probably has to be done in a separate commit.

Some tests were actually generating a flaky output, so they _are_ different now.

Interestingly, the regression test did _not_ flag these tests of being different even though the logfiles it produced are indeed different ... is there some fudging going on so that the differences are not seen ?

```diff
$ diff -uw ./tests/ArianeElab/ArianeElab.log ./build/regression/ArianeElab/ArianeElab.log | head -20
--- ./tests/ArianeElab/ArianeElab.log   2022-05-27 11:22:40.075820568 -0700
+++ ./build/regression/ArianeElab/ArianeElab.log        2022-05-27 11:41:22.081043455 -0700
@@ -43584,25 +43584,25 @@
       |vpiName:INT8
       |INT:0
       |vpiDecompile:0
-      |vpiSize:1
+      |vpiSize:2
     |vpiEnumConst:
     \_enum_const: (INT16), line:1550:5, endln:1550:10
       |vpiName:INT16
       |INT:1
       |vpiDecompile:1
-      |vpiSize:1
+      |vpiSize:2
     |vpiEnumConst:
     \_enum_const: (INT32), line:1551:5, endln:1551:10
       |vpiName:INT32
       |INT:2
       |vpiDecompile:2
```

**Comment by alaindargelas** [comment]
There is an issue with updating, the python script crashes for me.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alaindargelas** [comment]
I'm updating just the one test with count diff

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hzeller** [comment]
I also got a crash when running the regression script and have fixed it in #2973 - maybe this was also what you have seen ?

**Comment by alaindargelas** [comment]
Yes, that was it.

**Pull request merged**
