### PR TITLE
Few location and select parent fixes

### PR DESCRIPTION
**Pull request by hs-apotell**
Few location and select parent fixes

* Fixed bit_select/ref_obj parent for hier_paths
* Fill VpiSigned for var models
* Few location fixes, specifically for logic_typespec

### CODE REVIEW

**Comment by hs-apotell** [comment]
@alaindargelas Please review the changes carefully, specifically the change in CompileExpression.cpp dealing with parent for hier_path.

**Comment by alaindargelas** [comment]
Conflicting logs, please see comment in https://github.com/chipsalliance/Surelog/pull/2993

**Comment by alaindargelas** [comment]
@hs-apotell, please update the logs without IDs, merge all my changes, there are few diffs in the logs with my latest change: 
#2997

**Comment by hs-apotell** [comment]
@alaindargelas This change needs a closer look before merging. Please take a moment to review it closely.
Specific interesting changes in the logs -

From test ArianeElab -
```
          \_operation: , line:1410:25, endln:1410:38
            |vpiParent:
            \_part_select: , line:1410:16, endln:1410:41
            |vpiOpType:11
            |vpiOperand:
            \_ref_obj: (ariane_pkg::data_align::data_tmp::riscv::XLEN), line:1410:25, endln:1410:32
              |vpiParent:
              \_operation: , line:1410:25, endln:1410:38
              |vpiName:riscv::XLEN
              |vpiFullName:ariane_pkg::data_align::data_tmp::riscv::XLEN
              |vpiActual:
              \_parameter: (riscv::XLEN), line:15:16, endln:15:20
```
```
              |vpiOperand:
              \_ref_obj: (fpnew_pkg::fpnew_pkg::fpu_features_t::FpFmtMask::fmt_logic_t::NUM_FP_FORMATS), line:1528:20, endln:1528:34
                |vpiParent:
                \_operation: , line:1528:20, endln:1528:36
                |vpiName:NUM_FP_FORMATS
                |vpiFullName:fpnew_pkg::fpnew_pkg::fpu_features_t::FpFmtMask::fmt_logic_t::NUM_FP_FORMATS
```
```
             |vpiOperand:
              \_ref_obj: (fpnew_pkg::fpnew_pkg::fpu_features_t::IntFmtMask::ifmt_logic_t::NUM_INT_FORMATS), line:1566:20, endln:1566:35
                |vpiParent:
                \_operation: , line:1566:20, endln:1566:37
                |vpiName:NUM_INT_FORMATS
                |vpiFullName:fpnew_pkg::fpnew_pkg::fpu_features_t::IntFmtMask::ifmt_logic_t::NUM_INT_FORMATS
```

From ArrayVarName -
```
        \_bit_select: (work@top.get_a1.a), line:6:14, endln:6:18
          |vpiParent:
          \_ref_obj: (work@top.get_a1.a)
            |vpiParent:
            \_return_stmt: , line:6:7, endln:6:13
            |vpiName:a
            |vpiFullName:work@top.get_a1.a
            |vpiActual:
            \_array_var: (work@top.get_a1.a)
          |vpiName:a
          |vpiFullName:work@top.get_a1.a
          |vpiIndex:
          \_constant: , line:6:16, endln:6:17
```

Also, test _Ariane_ seems to be reporting a SEGFLT and unfortunately, this test runs only on Posix. Could you spare some cycles to investigate it?

**Comment by alaindargelas** [comment]
@hs-apotell by mixing completely different changes in the same PR you are making it impossible to review the diffs.
Why are you mixing column and line information change with vpiParent changes? Even reviewing one file is too difficult.

**Comment by alaindargelas** [comment]
Taking only the vpiParent parts of the PR, I found this change which is incorrect:

Screenshot from 2022-06-02 21-22-14

**Comment by alaindargelas** [comment]
this one too:

Screenshot from 2022-06-02 21-31-08

**Comment by alaindargelas** [comment]
Screenshot from 2022-06-02 21-46-54

**Comment by alaindargelas** [comment]
These are the only changes I took from your changelist and found the incorrect diffs above.
I also fixed the core dump:
```
+          if (member_ts)
+            member_ts->VpiParent(m);
```

```
alain@alain-xps:~/Surelog$ git diff .
diff --git a/src/DesignCompile/CompileExpression.cpp b/src/DesignCompile/CompileExpression.cpp
index 52f827669..a29550dbf 100644
--- a/src/DesignCompile/CompileExpression.cpp
+++ b/src/DesignCompile/CompileExpression.cpp
@@ -1161,21 +1161,46 @@ UHDM::any *CompileHelper::compileSelectExpression(
                 hier_path *p = (hier_path *)sel;
                 for (auto el : *p->Path_elems()) {
                   elems->push_back(el);
-                  el->VpiParent(path);
                   std::string n = el->VpiName();
                   if (el->UhdmType() == uhdmbit_select) {
-                    bit_select *s = (bit_select *)el;
-                    const expr *index = s->VpiIndex();
+                    bit_select *bs = (bit_select *)el;
+                    const expr *index = bs->VpiIndex();
                     std::string ind = index->VpiDecompile();
                     if (ind.empty()) ind = index->VpiName();
                     n += "[" + ind + "]";
+                    hname += "." + n;
+                    ref_obj *r = nullptr;
+                    if ((bs->VpiParent() != nullptr) &&
+                        (bs->VpiParent()->UhdmType() == uhdmref_obj)) {
+                      r = (ref_obj *)bs->VpiParent();
+                    } else {
+                      r = s.MakeRef_obj();
+                      bs->VpiParent(r);
+                    }
+                    r->VpiName(hname);
+                    r->VpiParent(path);
+                  } else {
+                    hname += "." + n;
+                    el->VpiParent(path);
                   }
-                  hname += "." + n;
                 }
                 break;
               } else {
+                if (sel->UhdmType() == uhdmbit_select) {
+                  ref_obj *r = nullptr;
+                  if ((sel->VpiParent() != nullptr) &&
+                      (sel->VpiParent()->UhdmType() == uhdmref_obj)) {
+                    r = (ref_obj *)sel->VpiParent();
+                  } else {
+                    r = s.MakeRef_obj();
+                    sel->VpiParent(r);
+                  }
+                  r->VpiName(sel->VpiName());
+                  r->VpiParent(path);
+                } else {
+                  sel->VpiParent(path);
+                }
                 elems->push_back(sel);
-                sel->VpiParent(path);
                 hname += "." + sel->VpiName();
               }
             }
@@ -4790,7 +4815,7 @@ UHDM::any *CompileHelper::compileComplexFuncCall(
               // Fix start/end to include the name
               select->VpiColumnNo(fC->Column(name));
               ref_obj *parent = (ref_obj *)select->VpiParent();
-              if (parent) parent->VpiDefName(tmpName);
+              if (parent) parent->VpiName(tmpName);
               if (tmpName.empty()) {
                 select->VpiParent(nullptr);
               }
diff --git a/src/DesignCompile/CompileStmt.cpp b/src/DesignCompile/CompileStmt.cpp
index 7cbf6ac02..83f59272c 100644
--- a/src/DesignCompile/CompileStmt.cpp
+++ b/src/DesignCompile/CompileStmt.cpp
@@ -671,8 +671,17 @@ VectorOfany* CompileHelper::compileStmt(DesignComponent* component,
       if (cond) {
         expr* exp =
             (expr*)compileExpression(component, fC, cond, compileDesign);
-        if (exp) exp->VpiParent(return_stmt);
-        return_stmt->VpiCondition(exp);
+        if (exp) {
+          if ((exp->VpiParent() != nullptr) &&
+              (exp->VpiParent()->UhdmType() == UHDM::uhdmref_obj) &&
+              ((exp->UhdmType() == UHDM::uhdmbit_select) ||
+               (exp->UhdmType() == UHDM::uhdmpart_select))) {
+            ((ref_obj*)exp->VpiParent())->VpiParent(return_stmt);
+          } else {
+            exp->VpiParent(return_stmt);
+          }
+          return_stmt->VpiCondition(exp);
+        }
       }
       stmt = return_stmt;
       break;
diff --git a/src/DesignCompile/CompileType.cpp b/src/DesignCompile/CompileType.cpp
index 0426849d9..bb6e21776 100644
--- a/src/DesignCompile/CompileType.cpp
+++ b/src/DesignCompile/CompileType.cpp
@@ -1478,6 +1478,8 @@ UHDM::typespec* CompileHelper::compileTypespec(
           m->VpiRefEndColumnNo(fC->EndColumn(Data_type));
           m->VpiParent(result);
           m->Typespec(member_ts);
+          if (member_ts)
+            member_ts->VpiParent(m);
           if (Expression && (fC->Type(Expression) != slVariable_dimension)) {
             any* ex =
                 compileExpression(component, fC, Expression, compileDesign,
(END)
```

Please revise your changelist (Only the part about vpiParent) to fix the issues I reported and resubmit it.
Please do not mix any other changes, you can submit those other changes in separate PRs.
Finding the issues above is only possible with targeted changes and targeted diffs.

**Comment by hs-apotell** [comment]
> @hs-apotell by mixing completely different changes in the same PR you are making it impossible to review the diffs. Why are you mixing column and line information change with vpiParent changes? Even reviewing one file is too difficult. I'm going to reject this PR. I'll take the change only related to vpiParent and create my own PR based on these changes that I'll merge. I'll let you submit **separate PRs** for:
> 
>     * vpiSigned
> 
>     * Column info change
> 
>     * the function return var change

These changes came from a different branch where the overarching goal was to improve RoundTrip results. I just pulled them into a different branch for PR. The changes were done over multiplication iterations over time. Either way, I will split the changes into multiple independent PR so the diffs are more manageable.

**Pull request closed without merging**
