### PR TITLE
IWYU: add some missing headers after NodeId/SymbolId header split.

### PR DESCRIPTION
**Pull request by hzeller**
Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hs-apotell** [comment]
Didn't the CI build successfully? Just so I don't miss these next time - how did you find them missing??

**Comment by hzeller** [comment]
Yes it compiled before in the CI, so it looked good there.

I tested if each header in itself is self-contained, so that discovered it. Maybe can add some CI using the [IWYU](https://include-what-you-use.org/) utility to determine these kind of things.

**Comment by hs-apotell** [comment]
> add some CI using the [IWYU](https://include-what-you-use.org/) utility

Yes, we should. If you got time, can you provide the exact command to use for Posix environment. Even better if you could add a CI build for it that would be great.

**Comment by hs-apotell** [comment]
Added #2981 to track.

**Pull request merged**
